fixed format. fixed selfsignedcertificate command.

diff --git a/cmd/azcertclient b/cmd/azcertclient
--- a/cmd/azcertclient
+++ b/cmd/azcertclient
@@ -2,15 +2,15 @@
 #--------------------------------------------------------------
 # Create client certification for VPN
 # You need to check this following URL.
-# https://docs.microsoft.com/ja-jp/azure/vpn-gateway/vpn-gateway-certificates-point-to-site-linux           
+# https://docs.microsoft.com/ja-jp/azure/vpn-gateway/vpn-gateway-certificates-point-to-site-linux
 #--------------------------------------------------------------
 set -e
 
 NAME=`basename $0`
 
 if [ $# -ne 2 ] ; then
-  echo "USAGE: $NAME {username} {password}"
-  exit 1
+    echo "USAGE: $NAME {username} {password}"
+    exit 1
 fi
 
 export PASSWORD=$2
@@ -22,8 +22,8 @@ CA_CERT=${SERVER_CERT_DIR}/caCert.pem
 CA_KEY=${SERVER_CERT_DIR}/caKey.pem
 
 if [ ! -f ${CA_CERT} -o ! -f ${CA_KEY} ] ; then
-  echo "Server Certification/Key file not found. Try again after creating server cert/key."
-  exit 1
+    echo "Server Certification/Key file not found. Try again after creating server cert/key."
+    exit 1
 fi
 
 USER_KEY="${TARGETDIR}/${USERNAME}Key.pem"
@@ -34,10 +34,10 @@ mkdir -p ${TARGETDIR}
 
 ipsec pki --gen --outform pem > "${USER_KEY}"
 ipsec pki --pub --in "${USER_KEY}" | \
-	ipsec pki --issue --cacert ${CA_CERT} --cakey ${CA_KEY} \
-	--dn "CN=${USERNAME}" --san "${USERNAME}" --flag clientAuth --outform pem \
-	--lifetime 3650 > "${USER_CERT}"
+ipsec pki --issue --cacert ${CA_CERT} --cakey ${CA_KEY} \
+--dn "CN=${USERNAME}" --san "${USERNAME}" --flag clientAuth --outform pem \
+--lifetime 3650 > "${USER_CERT}"
 openssl pkcs12 -in "${USER_CERT}" -inkey "${USER_KEY}" -certfile ${CA_CERT} \
-	-export -out "${USER_P12}" -password "pass:${PASSWORD}"
+-export -out "${USER_P12}" -password "pass:${PASSWORD}"
 
 echo "Created ${USER_P12}"
diff --git a/cmd/aztf b/cmd/aztf
--- a/cmd/aztf
+++ b/cmd/aztf
@@ -2,7 +2,7 @@
 #--------------------------------------------------------------
 # This script runs terraform command and create main_init.tf file.
 # main_init.tf generates terraform backend block and provider(azurerm/azuread).
-# 
+#
 # if you want to run this script, need to add this following environment.
 # - ENV
 # - ARM_CLIENT_ID
@@ -20,9 +20,9 @@ NAME=`basename $0`
 
 # usage function
 function usage () {
-  if [ ! -z $1 ]; then
-    echo "error: $(basename ${0}) needs $1 environment parameter."
-  fi
+    if [ ! -z $1 ]; then
+        echo "error: $(basename ${0}) needs $1 environment parameter."
+    fi
   cat <<EOF
 
 This script runs terraform command and create main_init.tf file.
@@ -32,11 +32,11 @@ Usage:
     $(basename ${0}) {commands} [<options>]
     $(basename ${0}) plan
     $(basename ${0}) apply
-    
+
 Options:
     same terraform command options
 EOF
-exit 1
+    exit 1
 }
 
 # script directory
@@ -46,51 +46,51 @@ SCRIPT_DIR=$(cd $(dirname $0); pwd)
 COMMAND=$@
 
 if [ -z $COMMAND ]; then
-  usage
+    usage
 fi
 # terraform-state key
 if [ -e "terraform-state.key" ]; then
-  KEY=`cat terraform-state.key | sed -e "s/[\r\n]\+//g"`
+    KEY=`cat terraform-state.key | sed -e "s/[\r\n]\+//g"`
 else
-  KEY=terraform-tfstate
+    KEY=terraform-tfstate
 fi
 
 # check environment
 if [ -z $ENV ]; then
-  usage ENV
-  exit 1
+    usage ENV
+    exit 1
 fi
 if [ -z $ARM_CLIENT_ID ]; then
-  usage ARM_CLIENT_ID
-  exit 1
+    usage ARM_CLIENT_ID
+    exit 1
 fi
 if [ -z $ARM_CLIENT_SECRET ]; then
-  usage ARM_CLIENT_SECRET
-  exit 1
+    usage ARM_CLIENT_SECRET
+    exit 1
 fi
 if [ -z $ARM_TENANT_ID ]; then
-  usage ARM_TENANT_ID
-  exit 1
+    usage ARM_TENANT_ID
+    exit 1
 fi
 if [ -z $ARM_SUBSCRIPTION_ID ]; then
-  usage ARM_SUBSCRIPTION_ID
-  exit 1
+    usage ARM_SUBSCRIPTION_ID
+    exit 1
 fi
 if [ -z $STORAGE_ACCOUNT_NAME ]; then
-  usage STORAGE_ACCOUNT_NAME
-  exit 1
+    usage STORAGE_ACCOUNT_NAME
+    exit 1
 fi
 if [ -z $RESOURCE_GROUP_NAME ]; then
-  usage RESOURCE_GROUP_NAME
-  exit 1
+    usage RESOURCE_GROUP_NAME
+    exit 1
 fi
 if [ -z $CONTAINER_NAME ]; then
-  usage CONTAINER_NAME
-  exit 1
+    usage CONTAINER_NAME
+    exit 1
 fi
 if [ -z $IS_GENERATE_PROVIDER ]; then
-  usage IS_GENERATE_PROVIDER
-  exit 1
+    usage IS_GENERATE_PROVIDER
+    exit 1
 fi
 
 # export TF_LOG=1
@@ -102,4 +102,4 @@ if [ $IS_GENERATE_PROVIDER -eq "1" ]; then
     cat ./main_init.tf | sed -i -e "s@##KEY##@${KEY}@g" ./main_init.tf
 fi
 terraform init
-terraform $COMMAND -var-file=terraform.$ENV.tfvars 
+terraform $COMMAND -var-file=terraform.$ENV.tfvars
diff --git a/cmd/gcptf b/cmd/gcptf
--- a/cmd/gcptf
+++ b/cmd/gcptf
@@ -2,7 +2,7 @@
 #--------------------------------------------------------------
 # This script runs terraform command and create main_init.tf file.
 # main_init.tf generates terraform backend block and provider(google/googlebeta).
-# 
+#
 # if you want to run this script, need to add this following environment.
 # - ENV
 # - BUCKET
@@ -19,9 +19,9 @@ NAME=`basename $0`
 
 # usage function
 function usage () {
-  if [ ! -z $1 ]; then
-    echo "error: $(basename ${0}) needs $1 environment parameter."
-  fi
+    if [ ! -z $1 ]; then
+        echo "error: $(basename ${0}) needs $1 environment parameter."
+    fi
   cat <<EOF
 
 This script runs terraform command and create main_init.tf file.
@@ -31,11 +31,11 @@ Usage:
     $(basename ${0}) {commands} [<options>]
     $(basename ${0}) plan
     $(basename ${0}) apply
-    
+
 Options:
     same terraform command options
 EOF
-exit 1
+    exit 1
 }
 
 # script directory
@@ -45,55 +45,55 @@ SCRIPT_DIR=$(cd $(dirname $0); pwd)
 COMMAND=$@
 
 if [ -z $COMMAND ]; then
-  usage
+    usage
 fi
 # terraform-state prefix
 if [ -e "terraform-state.prefix" ]; then
-  PREFIX=`cat terraform-state.prefix | sed -e "s/[\r\n]\+//g"`
+    PREFIX=`cat terraform-state.prefix | sed -e "s/[\r\n]\+//g"`
 else
-  PREFIX=terraform.tfstate
+    PREFIX=terraform.tfstate
 fi
 
 # check environment
 if [ -z $ENV ]; then
-  usage ENV
-  exit 1
+    usage ENV
+    exit 1
 fi
 if [ -z $BUCKET ]; then
-  usage BUCKET
-  exit 1
+    usage BUCKET
+    exit 1
 fi
 if [ -z $GOOGLE_CLOUD_KEYFILE_JSON ]; then
-  usage GOOGLE_CLOUD_KEYFILE_JSON
-  exit 1
+    usage GOOGLE_CLOUD_KEYFILE_JSON
+    exit 1
 fi
 if [ -z $PROJECT_ID ]; then
-  usage PROJECT_ID
-  exit 1
+    usage PROJECT_ID
+    exit 1
 fi
 if [ -z $REGION ]; then
-  usage ZONE
-  exit 1
+    usage ZONE
+    exit 1
 fi
 if [ -z $ZONE ]; then
-  usage ZONE
-  exit 1
+    usage ZONE
+    exit 1
 fi
 if [ -z $IS_GENERATE_PROVIDER ]; then
-  usage IS_GENERATE_PROVIDER
-  exit 1
+    usage IS_GENERATE_PROVIDER
+    exit 1
 fi
 
 # export TF_LOG=1
 # export TF_LOG_PATH='./terraform.log'
 rm -f terraform.log crash.log main_init.tf
 if [ $IS_GENERATE_PROVIDER -eq "1" ]; then
-  cat $SCRIPT_DIR/files/gcp/main.template.tf | sed -e "s/##BUCKET##/${BUCKET}/g" > ./main_init.tf
-  cat ./main_init.tf | sed -i -e "s@##PREFIX##@${PREFIX}@g" ./main_init.tf
-  cat ./main_init.tf | sed -i -e "s@##GOOGLE_CLOUD_KEYFILE_JSON##@${GOOGLE_CLOUD_KEYFILE_JSON}@g" ./main_init.tf
-  cat ./main_init.tf | sed -i -e "s/##PROJECT_ID##/${PROJECT_ID}/g" ./main_init.tf
-  cat ./main_init.tf | sed -i -e "s/##REGION##/${REGION}/g" ./main_init.tf
-  cat ./main_init.tf | sed -i -e "s/##ZONE##/${ZONE}/g" ./main_init.tf
+    cat $SCRIPT_DIR/files/gcp/main.template.tf | sed -e "s/##BUCKET##/${BUCKET}/g" > ./main_init.tf
+    cat ./main_init.tf | sed -i -e "s@##PREFIX##@${PREFIX}@g" ./main_init.tf
+    cat ./main_init.tf | sed -i -e "s@##GOOGLE_CLOUD_KEYFILE_JSON##@${GOOGLE_CLOUD_KEYFILE_JSON}@g" ./main_init.tf
+    cat ./main_init.tf | sed -i -e "s/##PROJECT_ID##/${PROJECT_ID}/g" ./main_init.tf
+    cat ./main_init.tf | sed -i -e "s/##REGION##/${REGION}/g" ./main_init.tf
+    cat ./main_init.tf | sed -i -e "s/##ZONE##/${ZONE}/g" ./main_init.tf
 fi
 terraform init
-terraform $COMMAND -var-file=terraform.$ENV.tfvars 
+terraform $COMMAND -var-file=terraform.$ENV.tfvars
